[package]
name = "IPSP-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ipsp_plugin"
crate-type = ["cdylib"]

[dependencies]
bluez-async = "0.6.0"